Milestone 10: Authentication with Devise gem
SaidRasinlic/Blog-App pull request #10
Opened 2022-08-05 22:01 UTC by SaidRasinlic

### In this milestone I've done the following things:

- Made sure that authentication is added for Sign In and Sign Up for an user.
-  Added look & feel for Views.
- Refactored code to use Rails best practices.

2022-08-05 22:18 UTC, elisha2kyakpo1 requested changes
Hi 👋 @SaidRasinlic, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The PR title and description looks professional✔️
- Descriptive commit messages✔️
- No linter errors✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-05 22:18 UTC, elisha2kyakpo1 commented on db/migrate/20220805151703_add_devise_to_users.rb
> +      # t.string   :confirmation_token
[ ] Kindly uncomment this part, remember we have confirmable in our user's model and we want user's to confirm their registration by email.

2022-08-06 11:23 UTC, SaidRasinlic commented on db/migrate/20220805151703_add_devise_to_users.rb
> +      # t.string   :confirmation_token
**Successfully uncommented confirmable for User's model ✔️.**

2022-08-06 11:56 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 🍷 

## Hi @SaidRasinlic 👋, 

Well done implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-06 14:25 UTC, merged